### ISSUE TITLE
is working now?

### ISSUE THREAD

**Issue by furacas** [mailway-app/mailway#17]
Recently my emails have failed to forward with 550 5.1.0 Requested action not taken: mailbox unavailable

and when i send email to support@mailway.app for help i got same error。

so are you still running this?

**Comment by m4p** [comment]
Just DMed the author on Twitter. He says he's not maintaining it anymore. ☹️

**Comment by xtuc** [comment]
Sorry for the inconvenience. I recommend migrating to Cloudflare's Email Routing service (which I'm working on).
