### ISSUE TITLE
Preflight Check Failing

### ISSUE THREAD

**Issue by andrewrkerr** [mailway-app/mailway#4]
**Issue:**
With Docker - unable to finish setup  due to port 25 being blocked. I'm failing the preflight check - port 25 is being blocked

**Steps Tried:**
Tried change the port being exposed by docker.
Tried using the nginx.conf file for SSL on port 465, but the docker container stops due to the preflight check before you can issue the command: mailway setup-secure-smtp

Do you have any suggestions or recommendations for a case when port 25 is blocked by ISP?

**Comment by xtuc** [comment]
Right now the port 25 is required by Mailway but I'm looking a solution that would fix that.

For now, my recommendation would be to host Mailway on a cloud provider that allows the port 25.
